---USUARIOS----
-- USUARIO SCHEMA DESAWEB
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER DESAWEB IDENTIFIED BY DESAWEB123;
GRANT CREATE SESSION, CREATE TABLE TO DESAWEB;

-- USUARIO OPERACION
CREATE USER OP_DESAWEB IDENTIFIED BY DESAWEB123;
GRANT CREATE SESSION TO OP_DESAWEB;
-- USUARIO CONSULTAS
CREATE USER USR_DESAWEB IDENTIFIED BY DESAWEB123;
GRANT CREATE SESSION TO USR_DESAWEB;

ALTER SESSION SET CURRENT_SCHEMA = DESAWEB;

CREATE TABLE ANULACION_VENTAS (
    COD_ANULACION    INTEGER NOT NULL,
    COD_NOTA_CREDITO INTEGER NOT NULL,
    COD_VENTA        INTEGER NOT NULL,
    MOTIVO_ANULACION VARCHAR2(250)
);

ALTER TABLE ANULACION_VENTAS ADD CONSTRAINT ANULACION_VENTAS_PK PRIMARY KEY ( COD_ANULACION );

CREATE TABLE CATEGORIA (
    COD_CATEGORIA INTEGER NOT NULL,
    NOMBRE        VARCHAR2(50),
    DESCRIPCION   VARCHAR2(250)
);

ALTER TABLE CATEGORIA ADD CONSTRAINT CATEGORIA_PK PRIMARY KEY ( COD_CATEGORIA );

CREATE TABLE CLIENTE(
    COD_CLIENTE       INTEGER NOT NULL,
    PRIMER_NOMBRE     VARCHAR2(75),
    SEGUNDO_NOMBRE    VARCHAR2(75),
    PRIMER_APELLIDO   VARCHAR2(75),
    SEGUNDO_APELLIDO  VARCHAR2(75),
    NIT               INTEGER,
    DIRECCION_CLIENTE VARCHAR2(100),
    CATEGORIA_CLIENTE INTEGER NOT NULL,
    STATUS            INTEGER NOT NULL
);

ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_PK PRIMARY KEY ( COD_CLIENTE );

CREATE TABLE DETALLE_VENTA (
    COD_DETALLE_VENTA       INTEGER NOT NULL,
    COD_VENTA               INTEGER NOT NULL,
    COD_PRODUCTO            INTEGER NOT NULL,
    CANTIDAD                NUMBER,
    SUBTOTAL                NUMBER,
    STATUS                  INTEGER,
    COD_DEVOLUCION_PRODUCTO INTEGER
);

ALTER TABLE DETALLE_VENTA ADD CONSTRAINT DETALLE_VENTA_PK PRIMARY KEY ( COD_DETALLE_VENTA );

CREATE TABLE DEVOLUCION_PRODUCTOS (
    COD_DEVOLUCION    INTEGER NOT NULL,
    COD_NOTA_CREDITO  INTEGER NOT NULL,
    CANTIDAD          NUMBER,
    MOTIVO_DEVOLUCION VARCHAR2(250)
);

ALTER TABLE DEVOLUCION_PRODUCTOS ADD CONSTRAINT DEVOLUCION_PRODUCTOS_PK PRIMARY KEY ( COD_DEVOLUCION );

CREATE TABLE ENTREGA_PAQUETE (
    COD_ENTREGA   INTEGER NOT NULL,
    DESCRIPCION   VARCHAR2(250),
    OBSERVACIONES VARCHAR2(250),
    COD_CLIENTE   INTEGER NOT NULL,
    COD_VENTA     INTEGER NOT NULL
);

ALTER TABLE ENTREGA_PAQUETE ADD CONSTRAINT ENTREGA_PAQUETE_PK PRIMARY KEY ( COD_ENTREGA );

CREATE TABLE NOTAS_CREDITO (
    COD_NOTA_CREDITO INTEGER NOT NULL,
    COD_CLIENTE      INTEGER NOT NULL,
    TIPO_NOTA        VARCHAR2(20),
    FECHA_NOTA       DATE,
    TOTAL            NUMBER,
    COD_VENTA        INTEGER NOT NULL
);

ALTER TABLE NOTAS_CREDITO ADD CONSTRAINT NOTAS_CREDITO_PK PRIMARY KEY ( COD_NOTA_CREDITO );

CREATE TABLE PRODUCTO (
    COD_PRODUCTO      INTEGER NOT NULL,
    DESCRIPCION       VARCHAR2(250),
    COD_PROVEEDOR     INTEGER NOT NULL,
    FECHA_VENCIMIENTO DATE,
    UBICACION         INTEGER NOT NULL,
    EXISTENCIA        INTEGER,
    PRECIO            INTEGER,
    STATUS            INTEGER
);

ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_PK PRIMARY KEY ( COD_PRODUCTO );

CREATE TABLE PROVEEDOR (
    COD_PROVEEDOR INTEGER NOT NULL,
    NOMBRE        VARCHAR2(50),
    DESCRIPCION   VARCHAR2(250)
);

ALTER TABLE PROVEEDOR ADD CONSTRAINT PROVEEDOR_PK PRIMARY KEY ( COD_PROVEEDOR );

CREATE TABLE STATUS_VENTA (
    COD_VENTA   INTEGER NOT NULL,
    NOMBRE      VARCHAR2(50),
    DESCRIPCION VARCHAR2(250)
);

ALTER TABLE STATUS_VENTA ADD CONSTRAINT STATUS_VENTA_PK PRIMARY KEY ( COD_VENTA );

CREATE TABLE UBICACION (
    COD_UBICACION INTEGER NOT NULL,
    NOMBRE        VARCHAR2(50),
    DESCRIPCION   VARCHAR2(250)
);

ALTER TABLE UBICACION ADD CONSTRAINT UBICACION_PK PRIMARY KEY ( COD_UBICACION );

CREATE TABLE VENTA (
    COD_VENTA           INTEGER NOT NULL,
    COD_CLIENTE         INTEGER NOT NULL,
    FECHA_VENTA         DATE,
    TOTAL_VENTA         NUMBER,
    STATUS_VENTA        INTEGER NOT NULL,
    COD_ANULACION_VENTA INTEGER
);

ALTER TABLE VENTA ADD CONSTRAINT VENTA_PK PRIMARY KEY ( COD_VENTA );

ALTER TABLE ANULACION_VENTAS
    ADD CONSTRAINT ANULACIONVENTA_NOTACREDITO_FK FOREIGN KEY ( COD_NOTA_CREDITO )
        REFERENCES NOTAS_CREDITO ( COD_NOTA_CREDITO );

ALTER TABLE ANULACION_VENTAS
    ADD CONSTRAINT ANULACION_VENTAS_VENTA_FK FOREIGN KEY ( COD_VENTA )
        REFERENCES VENTA ( COD_VENTA );

ALTER TABLE CLIENTES
    ADD CONSTRAINT CLIENTES_CATEGORIA_FK FOREIGN KEY ( CATEGORIA_CLIENTE )
        REFERENCES CATEGORIA ( COD_CATEGORIA );

ALTER TABLE DETALLE_VENTA
    ADD CONSTRAINT DETALLEVENTA_DEVOLUCIONPRODUCTO_FK FOREIGN KEY ( COD_DEVOLUCION_PRODUCTO )
        REFERENCES DEVOLUCION_PRODUCTOS ( COD_DEVOLUCION );

ALTER TABLE DETALLE_VENTA
    ADD CONSTRAINT DETALLE_VENTA_PRODUCTO_FK FOREIGN KEY ( COD_PRODUCTO )
        REFERENCES PRODUCTO ( COD_PRODUCTO );

ALTER TABLE DETALLE_VENTA
    ADD CONSTRAINT DETALLE_VENTA_VENTA_FK FOREIGN KEY ( COD_VENTA )
        REFERENCES VENTA ( COD_VENTA );

ALTER TABLE DEVOLUCION_PRODUCTOS
    ADD CONSTRAINT DEVOLUCIONPRODUCTO_NOTACREDITO_FK FOREIGN KEY ( COD_NOTA_CREDITO )
        REFERENCES NOTAS_CREDITO ( COD_NOTA_CREDITO );

ALTER TABLE ENTREGA_PAQUETE
    ADD CONSTRAINT ENTREGA_PAQUETE_CLIENTE_FK FOREIGN KEY ( COD_CLIENTE )
        REFERENCES CLIENTE( COD_CLIENTE );

ALTER TABLE ENTREGA_PAQUETE
    ADD CONSTRAINT ENTREGA_PAQUETE_VENTA_FK FOREIGN KEY ( COD_VENTA )
        REFERENCES VENTA ( COD_VENTA );

ALTER TABLE NOTAS_CREDITO
    ADD CONSTRAINT NOTAS_CREDITO_CLIENTE_FK FOREIGN KEY ( COD_CLIENTE )
        REFERENCES CLIENTE( COD_CLIENTE );

ALTER TABLE NOTAS_CREDITO
    ADD CONSTRAINT NOTAS_CREDITO_VENTA_FK FOREIGN KEY ( COD_VENTA )
        REFERENCES VENTA ( COD_VENTA );

ALTER TABLE PRODUCTO
    ADD CONSTRAINT PRODUCTO_PROVEEDOR_FK FOREIGN KEY ( COD_PROVEEDOR )
        REFERENCES PROVEEDOR ( COD_PROVEEDOR );

ALTER TABLE PRODUCTO
    ADD CONSTRAINT PRODUCTO_UBICACION_FK FOREIGN KEY ( UBICACION )
        REFERENCES UBICACION ( COD_UBICACION );

ALTER TABLE VENTA
    ADD CONSTRAINT VENTA_CLIENTE_FK FOREIGN KEY ( COD_CLIENTE )
        REFERENCES CLIENTE( COD_CLIENTE );

ALTER TABLE VENTA
    ADD CONSTRAINT VENTA_STATUS_VENTA_FK FOREIGN KEY ( STATUS_VENTA )
        REFERENCES STATUS_VENTA ( COD_VENTA );




CONNECT sys/Luis1234@localhost:1521/XE AS SYSDBA;

--PERMISOS DE USUARIOS 
--Usuario Operacion
GRANT SELECT, INSERT, UPDATE, DELETE ON DESAWEB.CLIENTE TO OP_DESAWEB;
GRANT SELECT, INSERT, UPDATE, DELETE ON DESAWEB.PRODUCTO TO OP_DESAWEB;
GRANT SELECT, INSERT, UPDATE, DELETE ON DESAWEB.VENTA TO OP_DESAWEB;
GRANT SELECT, INSERT, UPDATE, DELETE ON DESAWEB.DETALLE_VENTA TO OP_DESAWEB;
GRANT SELECT, INSERT, UPDATE, DELETE ON DESAWEB.ANULACION_VENTAS TO OP_DESAWEB;
GRANT SELECT, INSERT, UPDATE, DELETE ON DESAWEB.CATEGORIA TO OP_DESAWEB;
GRANT SELECT, INSERT, UPDATE, DELETE ON DESAWEB.DEVOLUCION_PRODUCTOS TO OP_DESAWEB;
GRANT SELECT, INSERT, UPDATE, DELETE ON DESAWEB.ENTREGA_PAQUETE TO OP_DESAWEB;
GRANT SELECT, INSERT, UPDATE, DELETE ON DESAWEB.NOTAS_CREDITO TO OP_DESAWEB;
GRANT SELECT, INSERT, UPDATE, DELETE ON DESAWEB.PROVEEDOR TO OP_DESAWEB;
GRANT SELECT, INSERT, UPDATE, DELETE ON DESAWEB.STATUS_VENTA TO OP_DESAWEB;
GRANT SELECT, INSERT, UPDATE, DELETE ON DESAWEB.UBICACION TO OP_DESAWEB;

--Usuario Consulta
GRANT SELECT ON DESAWEB.CLIENTE TO USR_DESAWEB;
GRANT SELECT ON DESAWEB.PRODUCTO TO USR_DESAWEB;
GRANT SELECT ON DESAWEB.VENTA TO USR_DESAWEB;
GRANT SELECT ON DESAWEB.DETALLE_VENTA TO USR_DESAWEB;
GRANT SELECT ON DESAWEB.ANULACION_VENTAS TO USR_DESAWEB;
GRANT SELECT ON DESAWEB.CATEGORIA TO USR_DESAWEB;
GRANT SELECT ON DESAWEB.DEVOLUCION_PRODUCTOS TO USR_DESAWEB;
GRANT SELECT ON DESAWEB.ENTREGA_PAQUETE TO USR_DESAWEB;
GRANT SELECT ON DESAWEB.NOTAS_CREDITO TO USR_DESAWEB;
GRANT SELECT ON DESAWEB.PROVEEDOR TO USR_DESAWEB;
GRANT SELECT ON DESAWEB.STATUS_VENTA TO USR_DESAWEB;
GRANT SELECT ON DESAWEB.UBICACION TO USR_DESAWEB;

--Sinonimos
--Usuario Operacion
CREATE SYNONYM OP_DESAWEB.CLIENTE FOR DESAWEB.CLIENTE;
CREATE SYNONYM OP_DESAWEB.PRODUCTO FOR DESAWEB.PRODUCTO;
CREATE SYNONYM OP_DESAWEB.VENTA FOR DESAWEB.VENTA;
CREATE SYNONYM OP_DESAWEB.DETALLE_VENTA FOR DESAWEB.DETALLE_VENTA;
CREATE SYNONYM OP_DESAWEB.ANULACION_VENTAS FOR DESAWEB.ANULACION_VENTAS;
CREATE SYNONYM OP_DESAWEB.CATEGORIA FOR DESAWEB.CATEGORIA;
CREATE SYNONYM OP_DESAWEB.DEVOLUCION_PRODUCTOS FOR DESAWEB.DEVOLUCION_PRODUCTOS;
CREATE SYNONYM OP_DESAWEB.ENTREGA_PAQUETE FOR DESAWEB.ENTREGA_PAQUETE;
CREATE SYNONYM OP_DESAWEB.NOTAS_CREDITO FOR DESAWEB.NOTAS_CREDITO;
CREATE SYNONYM OP_DESAWEB.PROVEEDOR FOR DESAWEB.PROVEEDOR;
CREATE SYNONYM OP_DESAWEB.STATUS_VENTA FOR DESAWEB.STATUS_VENTA;
CREATE SYNONYM OP_DESAWEB.UBICACION FOR DESAWEB.UBICACION;

--Usuario Consulta
CREATE SYNONYM USR_DESAWEB.CLIENTE FOR DESAWEB.CLIENTE;
CREATE SYNONYM USR_DESAWEB.PRODUCTO FOR DESAWEB.PRODUCTO;
CREATE SYNONYM USR_DESAWEB.VENTA FOR DESAWEB.VENTA;
CREATE SYNONYM USR_DESAWEB.DETALLE_VENTA FOR DESAWEB.DETALLE_VENTA;
CREATE SYNONYM USR_DESAWEB.ANULACION_VENTAS FOR DESAWEB.ANULACION_VENTAS;
CREATE SYNONYM USR_DESAWEB.CATEGORIA FOR DESAWEB.CATEGORIA;
CREATE SYNONYM USR_DESAWEB.DEVOLUCION_PRODUCTOS FOR DESAWEB.DEVOLUCION_PRODUCTOS;
CREATE SYNONYM USR_DESAWEB.ENTREGA_PAQUETE FOR DESAWEB.ENTREGA_PAQUETE;
CREATE SYNONYM USR_DESAWEB.NOTAS_CREDITO FOR DESAWEB.NOTAS_CREDITO;
CREATE SYNONYM USR_DESAWEB.PROVEEDOR FOR DESAWEB.PROVEEDOR;
CREATE SYNONYM USR_DESAWEB.STATUS_VENTA FOR DESAWEB.STATUS_VENTA;
CREATE SYNONYM USR_DESAWEB.UBICACION FOR DESAWEB.UBICACION;
