---USUARIOS----
-- USUARIO SCHEMA DESAWEB
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER DESAWEB IDENTIFIED BY DESAWEB123;
GRANT CREATE SESSION TO DESAWEB;
GRANT CREATE TABLE TO DESAWEB;
-- USUARIO OPERACION
CREATE USER OP_DESAWEB IDENTIFIED BY DESAWEB123;
GRANT CREATE SESSION TO OP_DESAWEB;
-- USUARIO CONSULTAS
CREATE USER USR_DESAWEB IDENTIFIED BY DESAWEB123;
GRANT CREATE SESSION TO USR_DESAWEB;

--PERMISOS DE USUARIOS 
--Usuario Operacion
GRANT INSERT, UPDATE, DELETE ON DESAWEB.CLIENTE TO OP_DESAWEB;
GRANT INSERT, UPDATE, DELETE ON DESAWEB.PRODUCTO TO OP_DESAWEB;
GRANT INSERT, UPDATE, DELETE ON DESAWEB.VENTA TO OP_DESAWEB;
GRANT INSERT, UPDATE, DELETE ON DESAWEB.DETALLE_VENTA TO OP_DESAWEB;
--Usuario Consulta
GRANT SELECT ON DESAWEB.CLIENTE TO USR_DESAWEB;
GRANT SELECT ON DESAWEB.PRODUCTO TO USR_DESAWEB;
GRANT SELECT ON DESAWEB.VENTA TO USR_DESAWEB;
GRANT SELECT ON DESAWEB.DETALLE_VENTA TO USR_DESAWEB;


--Sinonimos
--Usuario Operacion
CREATE SYNONYM CLIENTE FOR DESAWEB.CLIENTE;
CREATE SYNONYM PRODUCTO FOR DESAWEB.PRODUCTO;
CREATE SYNONYM VENTA FOR DESAWEB.VENTA;
CREATE SYNONYM DETALLE_VENTA FOR DESAWEB.DETALLE_VENTA;

--Usuario Consulta
CREATE SYNONYM CLIENTE FOR DESAWEB.CLIENTE;
CREATE SYNONYM PRODUCTO FOR DESAWEB.PRODUCTO;
CREATE SYNONYM VENTA FOR DESAWEB.VENTA;
CREATE SYNONYM DETALLE_VENTA FOR DESAWEB.DETALLE_VENTA;



-- TABLAS A CREAR -------------------------------------
-------------------------------------------------------
--CLIENTE----------------------------------------------

CREATE TABLE CLIENTE(
COD_CLIENTE INT,
PRIMER_NOMBRE VARCHAR2(75),
SEGUNDO_NOMBRE VARCHAR2(75),
PRIMER_APELLIDO VARCHAR2(75),
SEGUNDO_APELLIDO VARCHAR2(75),
NIT INT,
DIRECCION_CLIENTE VARCHAR(100),
CATEGORIA_CLIENTE INT,
STATUS CHAR(2),
);
--PRODUCTO ----------------------------------------------
--1 A MUCHOS CON DETALLE VENTA
CREATE TABLE PRODUCTO(
    COD_PRODUCTO INT,
    DESCRIPCION VARCHAR2(250),
    COD_PROVEEDOR INT,
    FECHA_VENCIMIENTO DATE,
    UBICACION INT,
    EXISTENCIA INT, 
    PRECIO INT,
    STATUS INT
);
--VENTA ----------------------------------------------
--1 A MUCHOS CON DETALLE VENTA
CREATE TABLE VENTA(
  COD_VENTA INT,
  COD_CLIENTE INT,
  FECHA_VENTA DATE,
  TOTAL_VENTA DECIMAL,
  STATUS_VENTA INT
);

--DETALLE VENTA ----------------------------------------------
CREATE TABLE DETALLE_VENTA(
  COD_DETALLE_VENTA INT,
  COD_VENTA INT,
  COD_PRODUCTO INT 
  CANTIDAD DECIMAL,
  SUBTOTAL DECIMAL,
);

-- Tabla NotasCredito
CREATE TABLE NOTAS_CREDITO(
    COD_NOTA_CREDITO INT PRIMARY KEY,
    COD_CLIENTE INT, -- Relación con el cliente que recibe la nota de crédito
    TIPO_NOTA VARCHAR2(20), -- Puede ser 'AnulacionVentas' o 'DevolucionProductos'
    FECHA_NOTA DATE,
    TOTAL DECIMAL,
    CONSTRAINT FK_CLIENTE_NOTA FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE)
);

-- Tabla para AnulacionVentas
CREATE TABLE ANULACION_VENTAS(
    COD_ANULACION INT PRIMARY KEY,
    COD_NOTA_CREDITO INT, -- Relación con la nota de crédito
    COD_VENTA INT, -- Relación con la venta que se está anulando
    MOTIVO_ANULACION VARCHAR2(250),
    CONSTRAINT FK_NOTA_ANULACION FOREIGN KEY (COD_NOTA_CREDITO) REFERENCES NOTAS_CREDITO (COD_NOTA_CREDITO),
    CONSTRAINT FK_VENTA_ANULACION FOREIGN KEY (COD_VENTA) REFERENCES VENTA (COD_VENTA)
);

-- Tabla para DevolucionProductos
CREATE TABLE DEVOLUCION_PRODUCTOS(
    COD_DEVOLUCION INT PRIMARY KEY,
    COD_NOTA_CREDITO INT, -- Relación con la nota de crédito
    COD_PRODUCTO INT, -- Relación con el producto que se está devolviendo
    CANTIDAD DECIMAL,
    MOTIVO_DEVOLUCION VARCHAR2(250),
    CONSTRAINT FK_NOTA_DEVOLUCION FOREIGN KEY (COD_NOTA_CREDITO) REFERENCES NOTAS_CREDITO (COD_NOTA_CREDITO),
    CONSTRAINT FK_PRODUCTO_DEVOLUCION FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTO (COD_PRODUCTO)
);



--DICCIONARIOS
--1 A MUCHOS EN CLIENTES
CREATE TABLE CATEGORIA(
  COD_CATEGORIA INT,
  NOMBRE VARCHAR2(50),   
  DESCRIPCION VARCHAR2(250)
);


-- 1 A MUCHOS EN VENTA
CREATE TABLE STATUS_VENTA(
  COD_VENTA INT,
  NOMBRE VARCHAR2(50),   
  DESCRIPCION VARCHAR2(250)  
);

--1 A MUCHOS PRODUCTOS
CREATE TABLE PROVEEDOR(
  COD_PROVEEDOR INT,
  NOMBRE VARCHAR2(50),   
  DESCRIPCION VARCHAR2(250)
);


--1 A MUCHOS EN PRODUCTO
CREATE TABLE UBICACION(
  COD_UBICACION INT,
  NOMBRE VARCHAR2(50),   
  DESCRIPCION VARCHAR2(250)
);



--INSERCIONES A BASE DE DATOS
--CLIENTES
INSERT INTO CLIENTE VALUES (,,,,,,);
--PRODUCTOS 
INSERT INTO PRODUCTO VALUES (,,,,,,);

-- CONSULTAS A BASE DE DATOS 
--CLIENTES
SELECT * FROM CLIENTE;
SELECT * FROM CLIENTE WHERE COD_CLIENTE= '';
SELECT * FROM CLIENTE WHERE PRIMER_NOMBRE = 'NOMBRE_BUSCADO' OR SEGUNDO_NOMBRE = 'NOMBRE_BUSCADO';
SELECT * FROM CLIENTE WHERE PRIMER_APELLIDO = 'NOMBRE_BUSCADO' OR SEGUNDO_APELLIDO = 'NOMBRE_BUSCADO';
SELECT * FROM CLIENTE WHERE NIT= '';
SELECT * FROM CLIENTE WHERE STATUS= '';
--PRODUCTOS
SELECT * FROM PRODUCTO;
--Por Codigo 
--Por Descripcion 
--Por Fecha de Vencimiento


--ACTUALIZACIONES DE TABLAS
--CLIENTES
UPDATE CLIENTE SET NOMBRE='' WHERE COD_CLIENTE=='';
UPDATE CLIENTE SET STATUS= 0  WHERE COD_CLIENTE=='';




--PRIMARY KEY
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY(COD_CLIENTE);
ALTER TABLE PRODUCTO ADD CONSTRAINT PK_PRODUCTO PRIMARY KEY(COD_PRODUCTO);
ALTER TABLE VENTA ADD CONSTRAINT PK_PRODUCTO PRIMARY KEY(COD_VENTA);
ALTER TABLE DETALLE_VENTA ADD CONSTRAINT PK_PRODUCTO PRIMARY KEY(COD_DETALLE_VENTA);
-- DE DICCIONARIOS
ALTER TABLE CATEGORIA ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY(COD_CATEGORIA);
ALTER TABLE PROVEEDOR ADD CONSTRAINT PK_PROVEEDOR PRIMARY KEY(COD_PROVEEDOR);
ALTER TABLE UBICACION ADD CONSTRAINT PK_UBICACION PRIMARY KEY(COD_UBICACION);

--BITACORA DE CAMBIOS

