-- Comando migrar solo una tabla
--dotnet ef dbcontext scaffold "User Id=OP_DESAWEB;Password=DESAWEB123;Data Source=34.172.95.117:1521/xe;" Oracle.EntityFrameworkCore -t BITACORA --context-dir DataAccess/ --output-dir DataAccess/Models --context ModelContext --force


--Secuencia
CREATE SEQUENCE SEQ_BITACORA START WITH 1 INCREMENT BY 1;

--ANULACION
CREATE OR REPLACE TRIGGER TRG_ANULACION_VENTAS_INSERT
AFTER INSERT ON ANULACION_VENTAS
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (
        SEQ_BITACORA.NEXTVAL,
        'ANULACION_VENTAS',
        'INSERT',
        :NEW.COD_ANULACION,
        USER,
        'Anulación de venta registrada con motivo de devolución: "' || :NEW.MOTIVO_ANULACION || '"'
    );
END;

CREATE OR REPLACE TRIGGER TRG_ANULACION_VENTAS_UPDATE
AFTER UPDATE ON ANULACION_VENTAS
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (
        SEQ_BITACORA.NEXTVAL,
        'ANULACION_VENTAS',
        'UPDATE',
        :OLD.COD_ANULACION,
        USER,
        'Campo cambiado: ' ||
        CASE 
            WHEN :OLD.COD_NOTA_CREDITO != :NEW.COD_NOTA_CREDITO THEN 'COD_NOTA_CREDITO de ' || :OLD.COD_NOTA_CREDITO || ' a ' || :NEW.COD_NOTA_CREDITO
            WHEN :OLD.MOTIVO_ANULACION != :NEW.MOTIVO_ANULACION THEN 'MOTIVO_ANULACION de "' || :OLD.MOTIVO_ANULACION || '" a "' || :NEW.MOTIVO_ANULACION || '"' 
            ELSE 'Sin cambios relevantes'
        END
    );
END;

CREATE OR REPLACE TRIGGER TRG_ANULACION_VENTAS_DELETE
AFTER DELETE ON ANULACION_VENTAS
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (SEQ_BITACORA.NEXTVAL, 'ANULACION_VENTAS', 'DELETE', :OLD.COD_ANULACION, USER, 'Registro eliminado');
END;

--CATEGORIA 

CREATE OR REPLACE TRIGGER TRG_CATEGORIA_INSERT
AFTER INSERT ON CATEGORIA
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (
        SEQ_BITACORA.NEXTVAL,
        'CATEGORIA',
        'INSERT',
        :NEW.COD_CATEGORIA,
        USER,
        'Categoría registrada con nombre: "' || :NEW.NOMBRE || '"'
    );
END;

CREATE OR REPLACE TRIGGER TRG_CATEGORIA_UPDATE
AFTER UPDATE ON CATEGORIA
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (
        SEQ_BITACORA.NEXTVAL,
        'CATEGORIA',
        'UPDATE',
        :OLD.COD_CATEGORIA,
        USER,
        'Campo cambiado: ' ||
        CASE 
            WHEN :OLD.NOMBRE != :NEW.NOMBRE THEN 'NOMBRE de "' || :OLD.NOMBRE || '" a "' || :NEW.NOMBRE || '"' 
            WHEN :OLD.DESCRIPCION != :NEW.DESCRIPCION THEN 'DESCRIPCION de "' || :OLD.DESCRIPCION || '" a "' || :NEW.DESCRIPCION || '"' 
            ELSE 'Sin cambios relevantes'
        END
    );
END;

CREATE OR REPLACE TRIGGER TRG_CATEGORIA_DELETE
AFTER DELETE ON CATEGORIA
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (SEQ_BITACORA.NEXTVAL, 'CATEGORIA', 'DELETE', :OLD.COD_CATEGORIA, USER, 'Registro eliminado');
END;

--CLIENTE

CREATE OR REPLACE TRIGGER TRG_CLIENTE_INSERT
AFTER INSERT ON CLIENTE
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (
        SEQ_BITACORA.NEXTVAL,
        'CLIENTE',
        'INSERT',
        :NEW.COD_CLIENTE,
        USER,
        'Cliente registrado con nombre: "' || :NEW.PRIMER_NOMBRE || ' ' || :NEW.PRIMER_APELLIDO || '"'
    );
END;

CREATE OR REPLACE TRIGGER TRG_CLIENTE_UPDATE
AFTER UPDATE ON CLIENTE
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (
        SEQ_BITACORA.NEXTVAL,
        'CLIENTE',
        'UPDATE',
        :OLD.COD_CLIENTE,
        USER,
        'Campo cambiado: ' ||
        CASE 
            WHEN :OLD.PRIMER_NOMBRE != :NEW.PRIMER_NOMBRE THEN 'PRIMER_NOMBRE de "' || :OLD.PRIMER_NOMBRE || '" a "' || :NEW.PRIMER_NOMBRE || '"'
            WHEN :OLD.DIRECCION_CLIENTE != :NEW.DIRECCION_CLIENTE THEN 'DIRECCION_CLIENTE de "' || :OLD.DIRECCION_CLIENTE || '" a "' || :NEW.DIRECCION_CLIENTE || '"'
            WHEN :OLD.STATUS != :NEW.STATUS THEN 'STATUS de ' || :OLD.STATUS || ' a ' || :NEW.STATUS
            ELSE 'Sin cambios relevantes'
        END
    );
END;

CREATE OR REPLACE TRIGGER TRG_CLIENTE_DELETE
AFTER DELETE ON CLIENTE
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (SEQ_BITACORA.NEXTVAL, 'CLIENTE', 'DELETE', :OLD.COD_CLIENTE, USER, 'Registro eliminado');
END;

--DETALLE VENTA 

CREATE OR REPLACE TRIGGER TRG_DETALLE_VENTA_INSERT
AFTER INSERT ON DETALLE_VENTA
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (SEQ_BITACORA.NEXTVAL, 'DETALLE_VENTA', 'INSERT', :NEW.COD_DETALLE_VENTA, USER, 'Registro insertado');
END;

CREATE OR REPLACE TRIGGER TRG_DETALLE_VENTA_UPDATE
AFTER UPDATE ON DETALLE_VENTA
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (
        SEQ_BITACORA.NEXTVAL,
        'DETALLE_VENTA',
        'UPDATE',
        :OLD.COD_DETALLE_VENTA,
        USER,
        'Campo cambiado: ' ||
        CASE 
            WHEN :OLD.CANTIDAD != :NEW.CANTIDAD THEN 'CANTIDAD de ' || :OLD.CANTIDAD || ' a ' || :NEW.CANTIDAD 
            WHEN :OLD.SUBTOTAL != :NEW.SUBTOTAL THEN 'SUBTOTAL de ' || :OLD.SUBTOTAL || ' a ' || :NEW.SUBTOTAL
            WHEN :OLD.STATUS != :NEW.STATUS THEN 'STATUS de ' || :OLD.STATUS || ' a ' || :NEW.STATUS
            ELSE 'Sin cambios relevantes'
        END
    );
END;

CREATE OR REPLACE TRIGGER TRG_DETALLE_VENTA_DELETE
AFTER DELETE ON DETALLE_VENTA
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (SEQ_BITACORA.NEXTVAL, 'DETALLE_VENTA', 'DELETE', :OLD.COD_DETALLE_VENTA, USER, 'Registro eliminado');
END;

--DEVOLUCION PRODUCTOS 

CREATE OR REPLACE TRIGGER TRG_DEVOLUCION_PRODUCTOS_INSERT
AFTER INSERT ON DEVOLUCION_PRODUCTOS
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (
        SEQ_BITACORA.NEXTVAL,
        'DEVOLUCION_PRODUCTOS',
        'INSERT',
        :NEW.COD_DEVOLUCION,
        USER,
        'Devolución de productos registrada con motivo: "' || :NEW.MOTIVO_DEVOLUCION || '"'
    );
END;

CREATE OR REPLACE TRIGGER TRG_DEVOLUCION_PRODUCTOS_UPDATE
AFTER UPDATE ON DEVOLUCION_PRODUCTOS
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (
        SEQ_BITACORA.NEXTVAL,
        'DEVOLUCION_PRODUCTOS',
        'UPDATE',
        :OLD.COD_DEVOLUCION,
        USER,
        'Campo cambiado: ' ||
        CASE 
            WHEN :OLD.CANTIDAD != :NEW.CANTIDAD THEN 'CANTIDAD de ' || :OLD.CANTIDAD || ' a ' || :NEW.CANTIDAD 
            WHEN :OLD.MOTIVO_DEVOLUCION != :NEW.MOTIVO_DEVOLUCION THEN 'MOTIVO_DEVOLUCION de "' || :OLD.MOTIVO_DEVOLUCION || '" a "' || :NEW.MOTIVO_DEVOLUCION || '"' 
            ELSE 'Sin cambios relevantes'
        END
    );
END;

CREATE OR REPLACE TRIGGER TRG_DEVOLUCION_PRODUCTOS_DELETE
AFTER DELETE ON DEVOLUCION_PRODUCTOS
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (SEQ_BITACORA.NEXTVAL, 'DEVOLUCION_PRODUCTOS', 'DELETE', :OLD.COD_DEVOLUCION, USER, 'Registro eliminado');
END;

--ENTREGA PAQUETES 
CREATE OR REPLACE TRIGGER TRG_ENTREGA_PAQUETE_INSERT
AFTER INSERT ON ENTREGA_PAQUETE
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (
        SEQ_BITACORA.NEXTVAL,
        'ENTREGA_PAQUETE',
        'INSERT',
        :NEW.COD_ENTREGA,
        USER,
        'Entrega de paquete registrada con descripción: "' || :NEW.DESCRIPCION || '"'
    );
END;

CREATE OR REPLACE TRIGGER TRG_ENTREGA_PAQUETE_UPDATE
AFTER UPDATE ON ENTREGA_PAQUETE
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (
        SEQ_BITACORA.NEXTVAL,
        'ENTREGA_PAQUETE',
        'UPDATE',
        :OLD.COD_ENTREGA,
        USER,
        'Campo cambiado: ' ||
        CASE 
            WHEN :OLD.DESCRIPCION != :NEW.DESCRIPCION THEN 'DESCRIPCION de "' || :OLD.DESCRIPCION || '" a "' || :NEW.DESCRIPCION || '"' 
            WHEN :OLD.OBSERVACIONES != :NEW.OBSERVACIONES THEN 'OBSERVACIONES de "' || :OLD.OBSERVACIONES || '" a "' || :NEW.OBSERVACIONES || '"'
            ELSE 'Sin cambios relevantes'
        END
    );
END;

CREATE OR REPLACE TRIGGER TRG_ENTREGA_PAQUETE_DELETE
AFTER DELETE ON ENTREGA_PAQUETE
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (SEQ_BITACORA.NEXTVAL, 'ENTREGA_PAQUETE', 'DELETE', :OLD.COD_ENTREGA, USER, 'Registro eliminado');
END;

--NOTAS CREDITO 
CREATE OR REPLACE TRIGGER TRG_NOTAS_CREDITO_INSERT
AFTER INSERT ON NOTAS_CREDITO
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (SEQ_BITACORA.NEXTVAL, 'NOTAS_CREDITO', 'INSERT', :NEW.COD_NOTA_CREDITO, USER, 'Registro insertado');
END;

CREATE OR REPLACE TRIGGER TRG_NOTAS_CREDITO_UPDATE
AFTER UPDATE ON NOTAS_CREDITO
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (
        SEQ_BITACORA.NEXTVAL,
        'NOTAS_CREDITO',
        'UPDATE',
        :OLD.COD_NOTA_CREDITO,
        USER,
        'Campo cambiado: ' ||
        CASE 
            WHEN :OLD.TOTAL != :NEW.TOTAL THEN 'TOTAL de ' || :OLD.TOTAL || ' a ' || :NEW.TOTAL
            WHEN :OLD.TIPO_NOTA != :NEW.TIPO_NOTA THEN 'TIPO_NOTA de "' || :OLD.TIPO_NOTA || '" a "' || :NEW.TIPO_NOTA || '"'
            ELSE 'Sin cambios relevantes'
        END
    );
END;

CREATE OR REPLACE TRIGGER TRG_NOTAS_CREDITO_DELETE
AFTER DELETE ON NOTAS_CREDITO
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (SEQ_BITACORA.NEXTVAL, 'NOTAS_CREDITO', 'DELETE', :OLD.COD_NOTA_CREDITO, USER, 'Registro eliminado');
END;

--PRODUCTO 
CREATE OR REPLACE TRIGGER TRG_PRODUCTO_INSERT
AFTER INSERT ON PRODUCTO
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (
        SEQ_BITACORA.NEXTVAL,
        'PRODUCTO',
        'INSERT',
        :NEW.COD_PRODUCTO,
        USER,
        'Producto registrado con descripción: "' || :NEW.DESCRIPCION || '"'
    );
END;

CREATE OR REPLACE TRIGGER TRG_PRODUCTO_UPDATE
AFTER UPDATE ON PRODUCTO
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (
        SEQ_BITACORA.NEXTVAL,
        'PRODUCTO',
        'UPDATE',
        :OLD.COD_PRODUCTO,
        USER,
        'Campo cambiado: ' ||
        CASE 
            WHEN :OLD.DESCRIPCION != :NEW.DESCRIPCION THEN 'DESCRIPCION de "' || :OLD.DESCRIPCION || '" a "' || :NEW.DESCRIPCION || '"'
            WHEN :OLD.PRECIO != :NEW.PRECIO THEN 'PRECIO de ' || :OLD.PRECIO || ' a ' || :NEW.PRECIO
            WHEN :OLD.EXISTENCIA != :NEW.EXISTENCIA THEN 'EXISTENCIA de ' || :OLD.EXISTENCIA || ' a ' || :NEW.EXISTENCIA
            ELSE 'Sin cambios relevantes'
        END
    );
END;

CREATE OR REPLACE TRIGGER TRG_PRODUCTO_DELETE
AFTER DELETE ON PRODUCTO
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (SEQ_BITACORA.NEXTVAL, 'PRODUCTO', 'DELETE', :OLD.COD_PRODUCTO, USER, 'Registro eliminado');
END;

--PROVEEDOR 

CREATE OR REPLACE TRIGGER TRG_PROVEEDOR_INSERT
AFTER INSERT ON PROVEEDOR
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (
        SEQ_BITACORA.NEXTVAL,
        'PROVEEDOR',
        'INSERT',
        :NEW.COD_PROVEEDOR,
        USER,
        'Proveedor registrado con nombre: "' || :NEW.NOMBRE || '"'
    );
END;

CREATE OR REPLACE TRIGGER TRG_PROVEEDOR_UPDATE
AFTER UPDATE ON PROVEEDOR
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (
        SEQ_BITACORA.NEXTVAL,
        'PROVEEDOR',
        'UPDATE',
        :OLD.COD_PROVEEDOR,
        USER,
        'Campo cambiado: ' ||
        CASE 
            WHEN :OLD.NOMBRE != :NEW.NOMBRE THEN 'NOMBRE de "' || :OLD.NOMBRE || '" a "' || :NEW.NOMBRE || '"'
            WHEN :OLD.DESCRIPCION != :NEW.DESCRIPCION THEN 'DESCRIPCION de "' || :OLD.DESCRIPCION || '" a "' || :NEW.DESCRIPCION || '"'
            ELSE 'Sin cambios relevantes'
        END
    );
END;

CREATE OR REPLACE TRIGGER TRG_PROVEEDOR_DELETE
AFTER DELETE ON PROVEEDOR
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (SEQ_BITACORA.NEXTVAL, 'PROVEEDOR', 'DELETE', :OLD.COD_PROVEEDOR, USER, 'Registro eliminado');
END;

--ESTATUS VENTA 

CREATE OR REPLACE TRIGGER TRG_STATUS_VENTA_INSERT
AFTER INSERT ON STATUS_VENTA
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (
        SEQ_BITACORA.NEXTVAL,
        'STATUS_VENTA',
        'INSERT',
        :NEW.COD_VENTA,
        USER,
        'Estatus de venta registrado con nombre: "' || :NEW.NOMBRE || '"'
    );
END;

CREATE OR REPLACE TRIGGER TRG_STATUS_VENTA_UPDATE
AFTER UPDATE ON STATUS_VENTA
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (
        SEQ_BITACORA.NEXTVAL,
        'STATUS_VENTA',
        'UPDATE',
        :OLD.COD_VENTA,
        USER,
        'Campo cambiado: ' ||
        CASE 
            WHEN :OLD.NOMBRE != :NEW.NOMBRE THEN 'NOMBRE de "' || :OLD.NOMBRE || '" a "' || :NEW.NOMBRE || '"'
            ELSE 'Sin cambios relevantes'
        END
    );
END;

CREATE OR REPLACE TRIGGER TRG_STATUS_VENTA_DELETE
AFTER DELETE ON STATUS_VENTA
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (SEQ_BITACORA.NEXTVAL, 'STATUS_VENTA', 'DELETE', :OLD.COD_VENTA, USER, 'Registro eliminado');
END;

--UBICACION 
CREATE OR REPLACE TRIGGER TRG_UBICACION_INSERT
AFTER INSERT ON UBICACION
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (
        SEQ_BITACORA.NEXTVAL,
        'UBICACION',
        'INSERT',
        :NEW.COD_UBICACION,
        USER,
        'Ubicación registrada con nombre: "' || :NEW.NOMBRE || '"'
    );
END;

CREATE OR REPLACE TRIGGER TRG_UBICACION_UPDATE
AFTER UPDATE ON UBICACION
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (
        SEQ_BITACORA.NEXTVAL,
        'UBICACION',
        'UPDATE',
        :OLD.COD_UBICACION,
        USER,
        'Campo cambiado: ' ||
        CASE 
            WHEN :OLD.NOMBRE != :NEW.NOMBRE THEN 'NOMBRE de "' || :OLD.NOMBRE || '" a "' || :NEW.NOMBRE || '"'
            WHEN :OLD.DESCRIPCION != :NEW.DESCRIPCION THEN 'DESCRIPCION de "' || :OLD.DESCRIPCION || '" a "' || :NEW.DESCRIPCION || '"'
            ELSE 'Sin cambios relevantes'
        END
    );
END;

CREATE OR REPLACE TRIGGER TRG_UBICACION_DELETE
AFTER DELETE ON UBICACION
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (SEQ_BITACORA.NEXTVAL, 'UBICACION', 'DELETE', :OLD.COD_UBICACION, USER, 'Registro eliminado');
END;


--VENTA

CREATE OR REPLACE TRIGGER TRG_VENTA_INSERT
AFTER INSERT ON VENTA
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (SEQ_BITACORA.NEXTVAL, 'VENTA', 'INSERT', :NEW.COD_VENTA, USER, 'Registro insertado');
END;

CREATE OR REPLACE TRIGGER TRG_VENTA_UPDATE
AFTER UPDATE ON VENTA
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (
        SEQ_BITACORA.NEXTVAL,
        'VENTA',
        'UPDATE',
        :OLD.COD_VENTA,
        USER,
        'Campo cambiado: ' ||
        CASE 
            WHEN :OLD.TOTAL_VENTA != :NEW.TOTAL_VENTA THEN 'TOTAL_VENTA de ' || :OLD.TOTAL_VENTA || ' a ' || :NEW.TOTAL_VENTA
            WHEN :OLD.STATUS_VENTA != :NEW.STATUS_VENTA THEN 'STATUS_VENTA de ' || :OLD.STATUS_VENTA || ' a ' || :NEW.STATUS_VENTA
            ELSE 'Sin cambios relevantes'
        END
    );
END;

CREATE OR REPLACE TRIGGER TRG_VENTA_DELETE
AFTER DELETE ON VENTA
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (ID_BITACORA, TABLA_NOMBRE, OPERACION, COD_REGISTRO, USUARIO, DESCRIPCION)
    VALUES (SEQ_BITACORA.NEXTVAL, 'VENTA', 'DELETE', :OLD.COD_VENTA, USER, 'Registro eliminado');
END;

